### PR TITLE
Add double-precision floating point feature 'use_f64'

### PR DESCRIPTION
**Pull request by ipadjen**
So, I opened the issue https://github.com/Twinklebear/tobj/issues/55, but then wrote the thing myself.

It's a feature 'use_double' that enables  switching the float type from f32 to f64.

### CODE REVIEW

**Comment by ipadjen** [comment]
I tried to keep it similar to tinyobjloader where they set the precision as a [cmake option](https://github.com/tinyobjloader/tinyobjloader/blob/0fc802cf468d23b9d205890b76b268f61b948e6d/CMakeLists.txt#L10).

Just like you said, I don't have a use case for loading both f32 and f64 in the same codebase. I deal mostly with geospatial data, so a roundoff error can be pretty significant with single-precision. I personally don't know of a case where someone would benefit from both?

As for CI tests, I have no idea what's going on with windows. I can take a look into features test in the next few days.

**Comment by Twinklebear** [comment]
Cool, yeah keeping it as a build option is fine with me, it will help avoid adding breaking changes to the API too.

I'll take a look at the windows failure, it's pretty odd. Maybe something changed w/ cfg if or some other package.

**Comment by ipadjen** [comment]
Alright, sounds good!

So, https://github.com/Twinklebear/tobj/pull/56/commits/4c9e45d2fa91a83aaa7423ec5d596a9fe2e8e1ea is my try to accommodate the tests. I added the [float_eq](https://crates.io/crates/float_eq) crate with a relative tolerance ([r2nd here](https://jtempest.github.io/float_eq-rs/book/background/float_comparison_algorithms.html)) of 1e-7 and changed all floating point assertions with it. I figured 7 decimal points would keep all the tests within the single-precision accuracy. I tried fiddling with the test values a bit, I think it seems fine.

**Comment by ipadjen** [comment]
Also, maybe 'use_f64' would sound more Rust than 'use_double'?

**Comment by Twinklebear** [comment]
I agree on `use_f64`, that matches the Rust type name so it'll be more what people expect 👍

**Comment by ipadjen** [comment]
I think the linux test should pass now with the updated formatting in https://github.com/Twinklebear/tobj/pull/56/commits/6cad6b3b7ee3fef8b3bfdf3e1328cfc67ebb00c1

**Comment by Twinklebear** [comment]
Cool! I think this looks good, I'll make some time to look into the windows/cfg-if specific issue

**Comment by Twinklebear** [comment]
Looks like the issue was that we actually were setting that split debug info flag in the Cargo.toml, and it seems to now be unstable/giving an error on windows when I don't think it was in the past. I've fixed that on master so I'll squash/rebase/merge this PR.

Thanks again @ipadjen !

**Comment by Twinklebear** [comment]
Actually, after doing that manual squash/merge/rebase github doesn't recognize this PR as being merged :/ . Would you mind squashing the commits down? Then I can just rebase it on to master w/ the GH UI.

**Comment by ipadjen** [comment]
There. Seems ready to merge now!

**Comment by Twinklebear** [comment]
Perfect, thanks @ipadjen !

**Pull request merged**
